### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by eduncan911** [hobeone/gonab#1]
Published 8 years ago, what is the status of this project?  :)

**Comment by hobeone** [comment]
At best, it's very very stale :)  I haven't touched it since then.

**Comment by eduncan911** [comment]
Whelp, my research shows that without membership to the private groups de-obfuscation routines, it's basically impossible to find and complete nzbs in the last 6 or so years.  nothing is public, and regex doesn't match much. 

maybe one day if I ever get back into the warez scene.  

you may want to archived this repo.  ;)

**Comment by hobeone** [comment]
Fair point.  I think there's others I need to do that to as well
